/**
 * Generated by PluginGenerator 1.7.0 from webgme on Thu Jun 23 2016 15:47:57 GMT-0500 (CDT).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */
import PluginBase = require('plugin/PluginBase');
declare class StreamingPlugin extends PluginBase {
    pluginMetadata: any;
    constructor();
    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    main(callback: PluginJS.Callback): void;
}
export = StreamingPlugin;
