/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Mon Dec 14 2015 15:14:56 GMT-0600 (CST).
 */

define([
    'plugin/PluginConfig',
    'plugin/PluginBase'
], function (
    PluginConfig,
    PluginBase) {
    'use strict';

    /**
     * Initializes a new instance of checkout.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin checkout.
     * @constructor
     */
    var checkout = function () {
        // Call base class' constructor.
        PluginBase.call(this);
    };

    // Prototypal inheritance from PluginBase.
    checkout.prototype = Object.create(PluginBase.prototype);
    checkout.prototype.constructor = checkout;

    /**
     * Gets the name of the checkout.
     * @returns {string} The name of the plugin.
     * @public
     */
    checkout.prototype.getName = function () {
        return 'checkout';
    };

    /**
     * Gets the semantic version (semver.org) of the checkout.
     * @returns {string} The version of the plugin.
     * @public
     */
    checkout.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
      Main function for the plugin to execute. This will perform the execution.
      Notes:
      - Always log with the provided logger.[error,warning,info,debug].
      - Do NOT put any user interaction logic UI, etc. inside this method.
      - callback always has to be called even if error happened.

      When this runs the core api is used to extract the meta-model and
      the model instance from the system multi-model. The multi-model contains
      all of the models used to describe the target system.
      The current model is replacd with the requested model.

     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    checkout.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            nodeObject;


        // Using the logger.
        self.logger.debug('This is a debug message.');
        self.logger.info('This is an info message.');
        self.logger.warn('This is a warning message.');
        self.logger.error('This is an error message.');

        // Using the coreAPI to make changes.

        nodeObject = self.activeNode;

        self.core.setAttribute(nodeObject, 'name', 'My new obj');
        self.core.setRegistry(nodeObject, 'position', {x: 70, y: 70});


        // This will save the changes. If you don't want to save;
        // exclude self.save and call callback directly from this scope.
        self.save('checkout updated model.', function (err) {
            if (err) {
                callback(err, self.result);
                return;
            }
            self.result.setSuccess(true);
            callback(null, self.result);
        });

    };

    return checkout;
});
